### ISSUE TITLE
Globální nastavení fn

### ISSUE THREAD

**Issue by Ikar4n** [3DprintFIT/B181HW-Assignment#10]
Nešlo by nastavit nějaké rozumné fn? 

Mám akorát problémy s boční dírou a šroubky prakticky v každém testu kde je vidět.
(reference, student, porovnání)
![fn comp](https://user-images.githubusercontent.com/28147977/50240794-07c0e200-03c6-11e9-8f79-e0693f3c6cd8.png)
![01a](https://user-images.githubusercontent.com/28147977/50240799-098aa580-03c6-11e9-9172-0e777f62f56e.png)
![01b](https://user-images.githubusercontent.com/28147977/50240803-0b546900-03c6-11e9-987c-fcc532418938.png)
![01c](https://user-images.githubusercontent.com/28147977/50240805-0c859600-03c6-11e9-9f83-bb547742799d.png)

**Comment by Ikar4n** [comment]
Tak problém dá se říct vyřešen, měl jsem cylindry otočený ještě o 90 stupňů podél osy Y...ale i tak by to nemuselo být na škodu.

**Comment by hroncok** [comment]
Obrázky kontrolujeme okometricky, není potřeba mít shodu per pixel, to číslo je debug informace.
