### ISSUE TITLE
Dotaz ke spodni casti

### ISSUE THREAD

**Issue by Kenny11CZ** [3DprintFIT/B181HW-Assignment#2]
Podle ceho se urcuje "hloubka" switche (te krabicky mezi hlavni krabickou a joystickem)? je tam uveden jen switch_height. A to same s vyskou te same casti.

**Comment by syky27** [comment]
@Kenny11CZ Dobrej point chybi na to parametr. V pondeli by to melo bejt updatnuty...

**Comment by Kenny11CZ** [comment]
Okey, diky ❤️

**Comment by marekreimer** [comment]
Hloubka tyhle kosticky nema samostatny parametr protoze je urcena uz jinymi parametry
![switch_joint_depth](https://user-images.githubusercontent.com/32454894/48667095-2e41e380-eacf-11e8-9b9a-1518915e668b.png)

**Comment by syky27** [comment]
mam pocit ze hloubka byla myslena smerem k Z=0

**Comment by Kenny11CZ** [comment]
Jakoze, obe mi tam chybeli, ted uz jen jedna 😄 tohoto jsem si nevsiml, moje chyba

**Comment by marekreimer** [comment]
V tom pripade je to polovina vysky spodni casti. A to by se nekde melo oznacit, to je pravda

**Comment by syky27** [comment]
@Kenny11CZ see #3 

Thanks...
