### ISSUE TITLE
Menší nesrovnalosti

### ISSUE THREAD

**Issue by pokorj54** [3DprintFIT/B181HW-Assignment#4]
V assembly_scheme.svg je označena šipkami dvakrát větší díra pro šroubek, ale se stejným popisem.

V bottom.svg je parametr bottom_base_thickness, který v požadovaném rozhraní není a místo něho je tam bottom_base_height

**Comment by marekreimer** [comment]
@pokorj54 Opravim

**Comment by marekreimer** [comment]
@pokorj54 Melo by byt opraveno v #5. V pripade dalsich nesrovnalosti/problemu otevri prosim nove issue
