### ISSUE TITLE
šířka konektoru k joysticku

### ISSUE THREAD

**Issue by mskl** [3DprintFIT/B181HW-Assignment#6]
Ahoj, čím je určena tahle velikost? Díky.
<img width="959" alt="snimek obrazovky 2018-11-19 v 3 29 59" src="https://user-images.githubusercontent.com/9153692/48683094-c90ff000-ebab-11e8-8117-7f470279feb5.png">

**Comment by mskl** [comment]
Nikde nevidím kótu, která by to vysvětlovala. Znamená to, že rozměr co hledám je zarovnaný s dírou předposledního knoflíku? Nebo prostředního?

**Comment by hroncok** [comment]
prostředního. plánujeme to dopsat do textu.
problém je, když je tam knoflík jen jeden, pak je totiž ta věc stále zarovnaná na ten předposlední (který tam ale není), tak řešíme, jak to vysvětlit, aby to nebylo jak definice z lineární algebry

**Comment by hroncok** [comment]
Snad lepší v https://github.com/3DprintFIT/B181HW-Assignment/pull/7

**Comment by mskl** [comment]
Fajn, takže je to ten předposlední. Díky.

**Comment by marekreimer** [comment]
Podle https://github.com/3DprintFIT/B181HW-Assignment/blob/master/xyz.svg.png?raw=true je to predposledni

**Comment by cernym46** [comment]
<img width="687" alt="screenshot 2018-12-06 at 17 31 20" src="https://user-images.githubusercontent.com/23376008/49597474-cd465680-f97c-11e8-8a45-3aefc884f6e2.png">

Podle issues je to druhý

**Comment by cernym46** [comment]
Jo, už tomu rozumím. Když se to bere od osy y, tak je to předposlední.
