### ISSUE TITLE
Výška šroubů

### ISSUE THREAD

**Issue by Ikar4n** [3DprintFIT/B181HW-Assignment#9]
<img width="755" alt="screen shot 2018-11-21 at 15 39 47" src="https://user-images.githubusercontent.com/28147977/48848316-e90a0400-eda3-11e8-856c-f4c09675c93c.png">
Jak je možné, že v testu 21 jsou v horním dílu nahoře od šroubů díry?

<img width="713" alt="screen shot 2018-11-21 at 15 50 57" src="https://user-images.githubusercontent.com/28147977/48848854-5702fb00-eda5-11e8-9ced-5db373e399eb.png">

**Comment by hroncok** [comment]
Good catch. Reference má chybu.

**Comment by hroncok** [comment]
Mám opravu, testuju, jestli se nic nerozbilo jinde.
